"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
  - source: /fastlane/metadata/android/en-US/title.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
